### ISSUE TITLE
VCML fails with newer gcc version

### ISSUE THREAD

**Issue by Robeast** [janweinstock/vcml#1]
Here is the warning which triggers the error with -Werror -> Tried under Ubuntu 14.04 and gcc 7.2

/home/pedram/mpsoc_vp/vcml/src/vcml/debugging/gdbserver.cpp: In member function ‘std::__cxx11::string vcml::debugging::gdbserver::handle_reg_write(const char*)’:
/home/pedram/mpsoc_vp/vcml/src/vcml/debugging/gdbserver.cpp:188:45: error: ‘<<’ in boolean context, did you mean ‘<’ ? [-Werror=int-in-bool-context]
             buffer[byte] = char2int(str[0]) << 4 || char2int(str[1]);
                            ~~~~~~~~~~~~~~~~^~~

/home/pedram/mpsoc_vp/vcml/src/vcml/debugging/gdbserver.cpp: In member function ‘std::__cxx11::string vcml::debugging::gdbserver::handle_reg_write_all(const char*)’:
/home/pedram/mpsoc_vp/vcml/src/vcml/debugging/gdbserver.cpp:230:49: error: ‘<<’ in boolean context, did you mean ‘<’ ? [-Werror=int-in-bool-context]
                 buffer[byte] = char2int(str[0]) << 4 || char2int(str[1]);

**Comment by janweinstock** [comment]
This should have been fixed in 13c1dab532a5df060b2afcdcb32a56b6d557f9f3. Could you please re-check  with the newest version?
