### ISSUE TITLE
Unused variable in sdcard.cpp

### ISSUE THREAD

**Issue by lasseUrban** [janweinstock/vcml#9]
Hi Jan,
in your sd card model there is the variable **m_maxblk** of type size_t (long unsigned int). The variable is set to -1 in the constructor and never changes its value. It is used in two comparisons in sd_data_read() and sd_data_write() but the condition can never become true. In my view you can just delete the variable. It is not necessary that the sd card knows the number of blocks that will be written or read. Due to this little flaw lines 84 (case SDTX_OK_COMPLETE) and 108 (SDRX_OK_COMPLETE) in spi2sd are never executed after WRITE_MULTIPLE_BLOCK and READ_MULTIPLE_BLOCK. But that is no big problem either.
Lasse

**Comment by janweinstock** [comment]
Hi Lasse,

`m_maxblk` was intended to be used for CMD23 (SET_BLOCK_COUNT), which specifies the number of blocks to read write with CMD18/25. Apparently the Linux driver does not use this command, but I still think we should provide support for an upper bound of reads/writes

**Comment by lasseUrban** [comment]
Hi Jan,
thank you for your response. I understand your demur. But, you merged the changings into master. m_maxblk is now deleted. I guess, this was a mistake?

**Comment by janweinstock** [comment]
No worries, the plan is to reintroduce `m_maxblk` when I add support for CMD23, hopefully soon.
